#### Regua Pow 3201 branca
- platform: mqtt
  name: "pow-3201 energy today"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Today }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "pow-3201 energy yesterday"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Yesterday }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "pow-3201 energy total"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Total }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "pow-3201 power"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Power }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "pow-3201 power factor"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Factor }}'
- platform: mqtt
  name: "pow-3201 voltage"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Voltage }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "pow-3201 current"
  state_topic: "tele/pow-3201/SENSOR"
  value_template: '{{ value_json.ENERGY.Current }}'
  unit_of_measurement: "A"

#### Regua 3202 branca
- platform: mqtt
  name: "pow-3202 energy today"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Today }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "pow-3202 energy yesterday"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Yesterday }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "pow-3202 energy total"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Total }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "pow-3202 power"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Power }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "pow-3202 power factor"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Factor }}'
- platform: mqtt
  name: "pow-3202 voltage"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Voltage }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "pow-3202 current"
  state_topic: "tele/pow-3202/SENSOR"
  value_template: '{{ value_json.ENERGY.Current }}'
  unit_of_measurement: "A"