###### Desliga bomba quando Tank1000 estive vazio
alias: "Tank1000 vazio - bomba off"
id: tank003
trigger:
  - platform: state
    entity_id: switch.tank1000_sensor_down
    to: 'on'
action: 
  service: switch.turn_off
  data:
    entity_id: switch.tank1000_relay               
        