###### Desliga bomba quando tank3000 estiver cheio.
alias: "Tank3000 cheio - bomba off"
id: tank002
trigger:
  - platform: state
    entity_id: switch.tank3000_sensor_up
    to: 'off'
condition:
  - condition: state
    entity_id: switch.tank3000_sensor_down
    state: 'off'
action: 
  service: switch.turn_off
  data:
    entity_id: switch.tank1000_relay               
    