###### Liga Bomba quando Tank3000 estiver vazio
alias: "Tank3000 vazio - bomba on"
id: tank001
trigger:
  - platform: state
    entity_id: switch.tank3000_sensor_down
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.tank3000_sensor_up
      state: 'on'
    - condition: state
      entity_id: switch.tank1000_sensor_down
      state: 'off'
action: 
  service: switch.turn_on
  data:
    entity_id: switch.tank1000_relay  
  
        