# - !include automations/alarm_set_away.yaml
# - !include automations/alarm_set_sleeping.yaml
# - !include automations/alarm_trigger.yaml
####PRESENCE BASED####
# - !include automations/away.yaml
# - !include automations/home_night_time.yaml
# - !include automations/home_day_time.yaml
# - !include automations/cmstormtrooper_on_home.yaml
# - !include automations/cmstormtrooper_off_away.yaml
# - !include automations/cmstormtrooper_off_sleeping.yaml
# - !include automations/car_finder_ben.yaml
# - !include automations/car_finder_cailin.yaml
# - !include automations/car_finder_ben_update_location.yaml
# - !include automations/car_finder_cailin_update_location.yaml
####SLEEP BASED####
# - !include automations/bed_sleeping.yaml
# - !include automations/cailin_sleeping.yaml
# - !include automations/morning_not_sleeping_light.yaml
# - !include automations/morning_not_sleeping_dark.yaml
# - !include automations/morning_not_sleeping_dark_one.yaml
####SUN BASED####
# - !include automations/sunrise_blinds.yaml
# - !include automations/sunset_all_on_not_cloudy.yaml
# - !include automations/sunset_all_on_cloudy.yaml
# - !include automations/sunset_blinds_closed_cloudy.yaml
# - !include automations/sunset_blinds_closed_not_cloudy.yaml
####MEDIA BASED####
# - !include automations/media_playing_night.yaml
# - !include automations/media_playing_day.yaml
# - !include automations/media_stopped_night.yaml
# - !include automations/media_stopped_day.yaml
####NOTIFICATION####
- !include automations/update_availible.yaml
- !include automations/owntracks_refresh.yaml
- !include automations/tank_check_hassio_start.yaml
####SENSOR BOMBA####
- !include automations/tank1000_sensordown_bomba_off.yaml
- !include automations/tank3000_sensorup_bomba_off.yaml
- !include automations/tank3000_sensordown_bomba_on.yaml
- !include automations/tank_teste.yaml
####SENSOR BASED####
# - !include automations/motion_night.yaml
# - !include automations/motion_bathroom.yaml
# - !include automations/low_battery.yaml
# - !include automations/clap_bedtime.yaml
# - !include automations/clap_morning.yaml
# - !include automations/driving_ben_start.yaml
# - !include automations/driving_ben_stop.yaml
####INPUT SELECT####
#- !include automations/lullaby.yaml
####PARTY BUTTON####
# - !include automations/party_button_restart_ha.yaml
# - !include automations/party_button_party_over.yaml
# - !include automations/party_button_party_time.yaml
# - !include automations/party_button_all_off.yaml
# - !include automations/party_button_sexy_time.yaml
####HYPERION automationsS####
# - !include automations/hyperion_mood_blobs_blue.yaml
# - !include automations/hyperion_knight_rider.yaml
# - !include automations/hyperion_mood_blobs_cold.yaml
# - !include automations/hyperion_mood_blobs_full_color.yaml
# - !include automations/hyperion_mood_blobs_green.yaml
# - !include automations/hyperion_mood_blobs_red.yaml
# - !include automations/hyperion_mood_blobs_warm.yaml
# - !include automations/hyperion_rainbow_mood.yaml
# - !include automations/hyperion_rainbow_swirl.yaml
# - !include automations/hyperion_snake.yaml
# - !include automations/hyperion_strobe_blue.yaml
# - !include automations/hyperion_strobe_white.yaml
# - !include automations/hyperion_strobe_raspberry.yaml
# - !include automations/hyperion_off.yaml
# - !include automations/hyperion_color_traces.yaml
# - !include automations/hyperion_snake.yaml
# - !include automations/hyperion_cinema_dim_lights.yaml
# - !include automations/hyperion_cinema_brighten_lights.yaml
# - !include automations/hyperion_police_lights_single.yaml
# - !include automations/hyperion_random.yaml
# - !include automations/hyperion_police_lights_solid.yaml
# - !include automations/hyperion_running_dots.yaml
# - !include automations/hyperion_system_shutdown.yaml
# - !include automations/hyperion_sparks_color.yaml
# - !include automations/hyperion_sparks.yaml

