- platform: yr
- platform: google_travel_time
  api_key: 'AIzaSyCkseeZQOzdMZFLMYkGfLZXtB3Okw2-320'
  origin: R. Palas, 656 - Pavuna, Rio de Janeiro - RJ
  destination: R. Maria Soares Sendas, 111 - Parque Barreto, São João de Meriti - RJ
  # destination: R. Nelsom da Silva, 663 - Distrito Industrial de Santa Cruz, Rio de Janeiro - RJ
- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'date_time'
  - 'time_date'
  - 'time_utc'
  - 'beat'
- platform: mqtt
  name: "zzzsonoff-2212 Temperatura C"
  state_topic: "tele/sonoff-2212/SENSOR"
  value_template: "{{ value_json.Temperature }}"
  unit_of_measurement: "C"
- platform: mqtt
  name: "zzzsonoff-2212 Humidade %"
  state_topic: "tele/sonoff-2212/SENSOR"
  value_template: "{{ value_json.Humidity }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "zzzsonoff-2212 Intensidade Luz %"
  state_topic: "tele/sonoff-2212/SENSOR"
  value_template: "{{ value_json.Light }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "zzzsonoff-2212 Ruido %"
  state_topic: "tele/sonoff-2212/SENSOR"
  value_template: "{{ value_json.Noise }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "zzzsonoff-2212 Qualidade do ar %"
  state_topic: "tele/sonoff-2212/SENSOR"
  value_template: "{{ value_json.AirQuality }}"
  unit_of_measurement: "%"
- platform: mqtt
  name: "wemosd1-2225 Temperatura C"
  state_topic: "tele/wemosd1-2225/SENSOR"
  value_template: "{{ value_json.SI7021.Temperature }}"
  unit_of_measurement: "C"
- platform: mqtt
  name: "wemosd1-2225 Humidade %"
  state_topic: "tele/wemosd1-2225/SENSOR"
  value_template: "{{ value_json.SI7021.Humidity }}"
  unit_of_measurement: "%"


  
 #### Regua Sonoff Pow regua branca
- platform: mqtt
  name: "sonoff-2296 energy today"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Today }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff-2296 energy yesterday"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Yesterday }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff-2296 energy total"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Total }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff-2296 power"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Power }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "sonoff-2296 power factor"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Factor }}'
- platform: mqtt
  name: "sonoff-2296 voltage"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Voltage }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "sonoff-2296 current"
  state_topic: "tele/sonoff-2296/SENSOR"
  value_template: '{{ value_json.ENERGY.Current }}'
  unit_of_measurement: "A"

 #### Regua Sonoff Pow regua laranja
- platform: mqtt
  name: "sonoff-2218 energy today"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Today }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff-2218 energy yesterday"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Yesterday }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff-2218 energy total"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Total }}'
  unit_of_measurement: "kWh"
- platform: mqtt
  name: "sonoff-2218 power"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Power }}'
  unit_of_measurement: "W"
- platform: mqtt
  name: "sonoff-2218 power factor"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Factor }}'
- platform: mqtt
  name: "sonoff-2218 voltage"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Voltage }}'
  unit_of_measurement: "V"
- platform: mqtt
  name: "sonoff-2218 current"
  state_topic: "tele/sonoff-2218/SENSOR"
  value_template: '{{ value_json.ENERGY.Current }}'
  unit_of_measurement: "A"

  
  # api_key: !secret forecast_api_key
  # monitored_conditions:
    # - summary
    # - precip_type
    # - precip_intensity
    # - precip_probability
    # - temperature
    # - apparent_temperature
    # - dew_point
    # - wind_speed
    # - wind_bearing
    # - cloud_cover
    # - humidity
    # - pressure
    # - visibility
  
  
  
  
  #  - platform: darksky
#    api_key: 'b15e1fea91c8f333889b46e73dd4d8f4'
#    monitored_conditions:
#      - summary
#      - icon
#      - nearest_storm_distance
#      - nearest_storm_bearing
#      - precip_type
#      - precip_intensity
#      - precip_probability
#      - temperature
#      - apparent_temperature
#      - dew_point
#      - wind_speed
#      - wind_bearing
#      - cloud_cover
#      - humidity
#      - pressure
#      - visibility
#      - ozone
#      - minutely_summary
#      - hourly_summary
#      - daily_summary
#      - temperature_max
#      - temperature_min
#      - apparent_temperature_max
#      - apparent_temperature_min
#      - precip_intensity_max
#  - platform: mqtt
#    name: "zzsonoff-pow energy"
#    state_topic: "tele/sonoff-workbench/ENERGY"
#    value_template: "{{ value_json.Today }}"
#    unit_of_measurement: "kWh"
#  - platform: mqtt
#    name: "zzsonoff-workbench power"
#    state_topic: "tele/sonoff-workbench/ENERGY"
#    value_template: "{{ value_json.Power }}"
#    unit_of_measurement: "W"
#  - platform: mqtt
#    name: "zzsonoff-workbench voltage"
#    state_topic: "tele/sonoff-workbench/ENERGY"
#    value_template: "{{ value_json.Voltage }}"
#    unit_of_measurement: "V"
